internet_shop/auth_app/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register_view, name='register')
]

internet_shop/internet_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cars/', include('trade_app.urls', namespace='cars')),
    url(r'^auth/', include('auth_app.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internet_shop/trade_app/urls.py
from django.conf.urls import url

from trade_app.views import *

urlpatterns = [
    url(r'^$', ProductsListView.as_view(), name='products_list'),
    url(r'^create/$', ProductsCreateView.as_view(), name='products_create'),
    url(r'^(?P<pk>[0-9]+)/$', ProductsDetailView.as_view(), name='product_details'),
    url(r'^(?P<pk>[0-9]+)/update/$', ProductsUpdateView.as_view(), name='products_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', ProductsDeleteView.as_view(), name='product_delete'),
    url(r'^(?P<pk>[0-9]+)/add_comment/$', product_add_comment_view, name='products_add_comment'),
    url(r'^spec/create/$', SpecificationsCreateView.as_view(), name='spec_create'),
    url(r'^spec/(?P<pk>[0-9]+)/$', SpecificationsDetailView.as_view(), name='spec_details'),
    url(r'^spec/(?P<pk>[0-9]+)/update/$', SpecificationsUpdateView.as_view(), name='spec_update'),
    url(r'^spec/(?P<pk>[0-9]+)/delete/$', SpecificationsDeleteView.as_view(), name='spec_delete'),
]

internet_shop/trade_app/models.py
from datetime import date
from os import remove

from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save, post_delete, pre_save
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth import get_user_model
from PIL import Image


def logo_upload_location(instance, filename):
    return 'logo/{0}/{1}'.format(date.today(), filename)


def preview_upload_location(instance, filename):
    return 'preview/{0}/{1}'.format(date.today(), filename)


class Product(models.Model):
    author = models.ForeignKey(get_user_model(), related_name='products')
    name = models.CharField(max_length=64, unique=True)
    logo = models.ImageField(upload_to=logo_upload_location, default=settings.DEFAULT_LOGO)
    preview = models.ImageField(upload_to=preview_upload_location, blank=True)
    description = models.TextField()
    min_price = models.PositiveIntegerField()
    rating = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-rating', 'name']

    def get_absolute_url(self):
        return reverse('cars:product_details', kwargs={'pk': self.id})

    def __str__(self):
        return self.name


class Comment(models.Model):
    author = models.ForeignKey(get_user_model(), related_name='comments')
    text = models.TextField()
    create_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.text


class Specification(models.Model):
    author = models.ForeignKey(get_user_model(), related_name='specifications')
    name = models.CharField(max_length=64)
    mark = models.CharField(max_length=32)
    model = models.CharField(max_length=32)
    engine_type = models.CharField(max_length=64)
    fuel_consumption = models.DecimalField(max_digits=5, decimal_places=2)
    horsepower = models.PositiveSmallIntegerField()
    max_speed = models.DecimalField(max_digits=5, decimal_places=2)
    GEARBOX = (
        (None, 'chose gearbox'),
        (4, 'four-speed'),
        (5, 'five-speed'),
        (6, 'six-speed'),
    )
    gearbox = models.PositiveSmallIntegerField(choices=GEARBOX)
    TYPE_OF_TRANSMISSION = (
        (None, 'chose type of transmission'),
        ('MT', 'manual transmission'),
        ('AT', 'automatic transmission')
    )
    transmission = models.CharField(max_length=2, choices=TYPE_OF_TRANSMISSION)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='specifications')

    class Meta:
        ordering = ['name']
        unique_together = (('name', 'mark', 'model'),)

    def get_absolute_url(self):
        return reverse('cars:spec_details', kwargs={'pk': self.id})

    def __str__(self):
        return self.name


@receiver(post_save, sender=Comment)
def calculate_rating(sender, **kwargs):
    product = Product.objects.get(id=kwargs.get('instance').product.id)
    product.rating = len(product.comments.all())
    product.save()


# @receiver(pre_save, sender=Product)
# def update_media_file(sender, **kwargs):
#     SIZE = (256, 256)
#     product = kwargs.get('instance')
#     old_logo = sender.objects.get(id=product.id).logo
#     logo = Image.open(old_logo.path).copy()
#     logo.thumbnail(SIZE)
#     logo.save('', 'JPEG')
#     product.preview = location
#     try:
#         remove(old_logo.path)
#     except:
#         pass


@receiver(post_delete, sender=Product)
def delete_media_file(sender, **kwargs):
    instance = kwargs.get("instance")
    instance.logo.delete(save=False)
    instance.preview.delete(save=False)

internet_shop/trade_app/forms.py
from django import forms
from django.utils.translation import ugettext_lazy
from functools import partial

from trade_app.models import Product, Comment, Specification


def get_choices(model, field):
    set_of_field = set([eval('object.' + field) for object in model.objects.all()])
    choices = tuple([(field, field) for field in set_of_field])
    choices = (('', 'all'), ) + choices
    return choices


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'logo', 'description', 'min_price']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 10}),
        }
        labels = {
            'min_price': ugettext_lazy('Price from'),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['author', 'text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 10}),
        }


class SpecificationForm(forms.ModelForm):

    class Meta:
        model = Specification
        fields = '__all__'


class ProductSearchForm(forms.Form):
    GEARBOX = (
        ('', 'all'),
        (4, 'four-speed'),
        (5, 'five-speed'),
        (6, 'six-speed'),
    )
    TYPE_OF_TRANSMISSION = (
        ('', 'all'),
        ('MT', 'manual transmission'),
        ('AT', 'automatic transmission')
    )
    name = forms.ChoiceField(choices=partial(get_choices, Specification, 'name'), required=False)
    mark = forms.ChoiceField(choices=partial(get_choices, Specification, 'mark'), required=False)
    model = forms.ChoiceField(choices=partial(get_choices, Specification, 'model'), required=False)
    engine_type = forms.ChoiceField(choices=partial(get_choices, Specification, 'engine_type'), required=False)
    gearbox = forms.ChoiceField(choices=GEARBOX, required=False)
    transmission = forms.ChoiceField(choices=TYPE_OF_TRANSMISSION, required=False)

internet_shop/trade_app/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_http_methods
from django.views import generic
from django.urls import reverse_lazy

from trade_app.models import Product, Comment, Specification
from trade_app.forms import ProductForm, CommentForm, SpecificationForm, ProductSearchForm


# All about Products ----------------------------
class ProductsListView(generic.ListView):
    model = Product
    template_name = 'product_list.html'

    def get_queryset(self):
        attrs = self.request.GET
        if attrs.get('car_name'):
            queryset = Product.objects.filter(name__icontains=attrs.get('car_name'))
        elif len(attrs) > 1:
            # to group data by using distinct .order_by('product_id').distinct('product_id')
            specs = Specification.objects.filter(
                name__icontains=attrs.get('name'),
                mark__icontains=attrs.get('mark'),
                model__icontains=attrs.get('model'),
                engine_type__icontains=attrs.get('engine_type'),
                transmission__icontains=attrs.get('transmission')
            )
            if attrs.get('gearbox'):
                specs = specs.filter(
                    specifications__gearbox=int(attrs.get('gearbox'))
                )
            queryset = Product.objects.filter(pk__in=specs.values('product_id'))
        else:
            queryset = super(ProductsListView, self).get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['search_form'] = ProductSearchForm()
        return context


class ProductsDetailView(generic.DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductsDetailView, self).get_context_data(**kwargs)
        product = get_object_or_404(
            Product.objects.prefetch_related('specifications', 'comments'),
            id=self.kwargs.get('pk')
        )
        context['product'] = product
        context['comment_form'] = CommentForm()
        return context


class ProductsCreateView(generic.CreateView):
    form_class = ProductForm
    template_name = 'product_form.html'

    def get_success_url(self):
        return self.object.get_absolute_url()


class ProductsUpdateView(generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_form.html'

    def get_success_url(self):
        return self.object.get_absolute_url()


class ProductsDeleteView(generic.DeleteView):
    model = Product
    success_url = reverse_lazy('cars:products_list')


@require_http_methods(['POST'])
def product_add_comment_view(request, pk):
    product = Product.objects.get(id=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.product = product
        instance.save()
    return redirect(product)


# All about Specifications ----------------------
class SpecificationsCreateView(generic.CreateView):
    form_class = SpecificationForm
    template_name = 'specification_form.html'
    success_url = reverse_lazy('cars:products_list')


class SpecificationsDetailView(generic.DetailView):
    model = Specification


class SpecificationsUpdateView(generic.UpdateView):
    model = Specification
    form_class = SpecificationForm
    template_name = 'specification_form.html'

    def get_success_url(self):
        return self.object.get_absolute_url()


class SpecificationsDeleteView(generic.DeleteView):
    model = Specification
    success_url = reverse_lazy('cars:products_list')

internet_shop/templates/trade_app/object_delete.html
{% load staticfiles %}
<form method="post" action="{% url url_name pk=object.id %}">{% csrf_token %}
    <button type="button" class="btn btn-light" style="float: right;" data-toggle="modal" data-target="#exampleModal">
        <img src="{% static 'img/garbage.png' %}" height="25">
    </button>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Attention!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Are you sure that you want to delete?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-danger">Delete</button>
          </div>
        </div>
      </div>
    </div>
</form>

internet_shop/templates/trade_app/product_detail.html
{% extends 'base.html'%}
{% load staticfiles %}
{% load humanize %}
{% block content %}
    {% include "object_delete.html" with url_name='cars:product_delete' %}
    <div style="float: right;">
        <div class="btn btn-light">
            <a href="{% url 'cars:products_update' pk=object.id %}">
                <img src="{% static 'img/edit.svg' %}" height="25">
            </a>
        </div>
    </div>
    <h2>{{ object.name }}</h2>
    <a href="{{ object.logo.url }}"><img src="{{ object.logo.url }}" alt="Car preview" height="300px"></a>
    <h2>Description:</h2>
    <h5>{{ object.description }}</h5>
    <h2>Price from {{ object.min_price|intcomma }}$</h2>
    <h2>Specifications:</h2>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        {% for spec in object.specifications.all %}
            <li class="nav-item">
            {% if spec == object.specifications.all.1 %}
                <a class="nav-link active" id="{{ spec.name }}-tab" data-toggle="tab" href="#{{ spec.name }}" role="tab" aria-controls="{{ spec.name }}" aria-selected="true">{{ spec.name }}</a>
            {% elif object.specifications.all|length_is:"1" %}
                <a class="nav-link active" id="{{ spec.name }}-tab" data-toggle="tab" href="#{{ spec.name }}" role="tab" aria-controls="{{ spec.name }}" aria-selected="true">{{ spec.name }}</a>
            {% else %}
                <a class="nav-link" id="{{ spec.name }}-tab" data-toggle="tab" href="#{{ spec.name }}" role="tab" aria-controls="{{ spec.name }}" aria-selected="false">{{ spec.name }}</a>
            {% endif %}
            </li>
        {% endfor %}
    </ul>
    <div class="tab-content" id="myTabContent">
        {% for spec in object.specifications.all %}
            {% if spec == object.specifications.all.1 %}
                <div class="tab-pane fade show active" id="{{ spec.name }}" role="tabpanel" aria-labelledby="{{ spec.name }}-tab">{% include "specification_detail.html" with spec=spec%}</div>
            {% elif object.specifications.all|length_is:"1" %}
                <div class="tab-pane fade show active" id="{{ spec.name }}" role="tabpanel" aria-labelledby="{{ spec.name }}-tab">{% include "specification_detail.html" with spec=spec%}</div>
            {% else %}
                <div class="tab-pane fade" id="{{ spec.name }}" role="tabpanel" aria-labelledby="{{ spec.name }}-tab">{% include "specification_detail.html" with spec=spec %}</div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock content%}

internet_shop/templates/trade_app/product_form.html
{% extends 'base.html'%}
{% block content %}
    <h2>Add new car</h2>
    <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Save" />
    </form>
{% endblock content%}

internet_shop/templates/trade_app/product_list.html
{% extends 'base.html'%}
{% block content %}
    <form class="form-inline my-2 my-lg-0" method="get" action="">
        <input name="car_name" class="form-control mr-sm-2" type="search" placeholder="Search by car name" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <div id="exampleAccordion" data-children=".item">
        <div class="item">
            <a data-toggle="collapse" data-parent="#exampleAccordion" href="#exampleAccordion1" aria-expanded="true" aria-controls="exampleAccordion1">
                search by specification
            </a>
            <div id="exampleAccordion1" class="collapse" role="tabpanel">
                <p class="mb-3">
                    <form class="form my-2 my-lg-0" method="get" action="">
                        {{ search_form.as_p }}
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </p>
            </div>
        </div>
    </div>
    {% for car in object_list %}
        <div class="card" style="width: 20rem;">
            <img class="card-img-top" src="{{ car.logo.url }}" alt="Card image cap">
            <div class="card-body">
                <h4 class="card-title">{{ car.name }}</h4>
                <p class="card-text">{{ car.description|truncatechars:130 }}</p>
                <a href="{% url 'cars:product_details' pk=car.id %}" class="btn btn-primary">Read more ...</a>
            </div>
        </div><br>
    {% endfor %}
{% endblock content%}

internet_shop/templates/trade_app/specification_detail.html
{% load staticfiles %}
<form method="post" action="{% url 'cars:spec_delete' pk=spec.id %}">{% csrf_token %}
    <div style="float: right;">
        <button type="submit" class="btn btn-light"><img src="{% static 'img/garbage.png' %}" height="25"></button>
    </div>
</form>
<div style="float: right;">
    <button type="button" class="btn btn-light">
        <a href="{% url 'cars:spec_update' pk=spec.id %}">
            <img src="{% static 'img/edit.svg' %}" height="25">
        </a>
    </button>
</div>
<p><b>Mark:</b> {{ spec.mark }}</p>
<p><b>Model:</b> {{ spec.model }}</p>
<p><b>Engine:</b> {{ spec.engine_type }}</p>
<p><b>Fuel consumption:</b> {{ spec.fuel_consumption }} L/100km</p>
<p><b>Horsepower:</b> {{ spec.horsepower }} horses</p>
<p><b>Max speed:</b> {{ spec.max_speed }} km/h</p>
<p><b>Gearbox:</b> {{ spec.get_gearbox_display }}</p>
<p><b>Transmission:</b> {{ spec.get_transmission_display }}({{ spec.transmission }})</p>

internet_shop/templates/trade_app/specification_form.html
{% extends 'base.html'%}
{% block content %}
    <h2>Add new specification</h2>
    <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Save" />
    </form>
{% endblock content%}