internet_shop/auth_app/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register_view, name='register')
]

internet_shop/internet_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cars/', include('trade_app.urls', namespace='cars')),
    url(r'^auth/', include('auth_app.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internet_shop/trade_app/urls.py
from django.conf.urls import url

from trade_app.views import *

urlpatterns = [
    url(r'^$', ProductsListView.as_view(), name='products_list'),
    url(r'^create/$', ProductsCreateView.as_view(), name='products_create'),
    url(r'^(?P<pk>[0-9]+)/$', ProductsDetailView.as_view(), name='product_details'),
    url(r'^(?P<pk>[0-9]+)/update/$', ProductsUpdateView.as_view(), name='products_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', ProductsDeleteView.as_view(), name='product_delete'),
    url(r'^(?P<pk>[0-9]+)/add_comment/$', product_add_comment_view, name='products_add_comment'),
    url(r'^spec/create/$', SpecificationsCreateView.as_view(), name='spec_create'),
    url(r'^spec/(?P<pk>[0-9]+)/$', SpecificationsDetailView.as_view(), name='spec_details'),
    url(r'^spec/(?P<pk>[0-9]+)/update/$', SpecificationsUpdateView.as_view(), name='spec_update'),
    url(r'^spec/(?P<pk>[0-9]+)/delete/$', SpecificationsDeleteView.as_view(), name='spec_delete'),
]

internet_shop/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mazda{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:login' %}">Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:register' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars:products_list' %}">Cars</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars:products_create'%}">Add car</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars:spec_create'%}">Add specification</a>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}
<div class="col-md-4 offset-md-4">
{% block content %}{% endblock %}
</div>
{% block index %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>